# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communication.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x63ommunication.proto\"\x0f\n\rCommunicationb\x06proto3')
)




_COMMUNICATION = _descriptor.Descriptor(
  name='Communication',
  full_name='Communication',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=38,
)

DESCRIPTOR.message_types_by_name['Communication'] = _COMMUNICATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Communication = _reflection.GeneratedProtocolMessageType('Communication', (_message.Message,), dict(
  DESCRIPTOR = _COMMUNICATION,
  __module__ = 'communication_pb2'
  # @@protoc_insertion_point(class_scope:Communication)
  ))
_sym_db.RegisterMessage(Communication)


# @@protoc_insertion_point(module_scope)
