# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grid_protection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grid_protection.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15grid_protection.proto\"\xc3\x01\n\x0eGridProtection\x12:\n\x11grid_monitor_time\x18\x05 \x01(\x0b\x32\x1f.GridProtection.GridMonitorTime\x12&\n\x06header\x18\t \x01(\x0b\x32\x16.GridProtection.Header\x1a \n\x0fGridMonitorTime\x12\r\n\x05value\x18\x01 \x01(\x05\x1a+\n\x06Header\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x05\x62\x06proto3')
)




_GRIDPROTECTION_GRIDMONITORTIME = _descriptor.Descriptor(
  name='GridMonitorTime',
  full_name='GridProtection.GridMonitorTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='GridProtection.GridMonitorTime.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=176,
)

_GRIDPROTECTION_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='GridProtection.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serial', full_name='GridProtection.Header.serial', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='GridProtection.Header.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=221,
)

_GRIDPROTECTION = _descriptor.Descriptor(
  name='GridProtection',
  full_name='GridProtection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='grid_monitor_time', full_name='GridProtection.grid_monitor_time', index=0,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='header', full_name='GridProtection.header', index=1,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GRIDPROTECTION_GRIDMONITORTIME, _GRIDPROTECTION_HEADER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=221,
)

_GRIDPROTECTION_GRIDMONITORTIME.containing_type = _GRIDPROTECTION
_GRIDPROTECTION_HEADER.containing_type = _GRIDPROTECTION
_GRIDPROTECTION.fields_by_name['grid_monitor_time'].message_type = _GRIDPROTECTION_GRIDMONITORTIME
_GRIDPROTECTION.fields_by_name['header'].message_type = _GRIDPROTECTION_HEADER
DESCRIPTOR.message_types_by_name['GridProtection'] = _GRIDPROTECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GridProtection = _reflection.GeneratedProtocolMessageType('GridProtection', (_message.Message,), dict(

  GridMonitorTime = _reflection.GeneratedProtocolMessageType('GridMonitorTime', (_message.Message,), dict(
    DESCRIPTOR = _GRIDPROTECTION_GRIDMONITORTIME,
    __module__ = 'grid_protection_pb2'
    # @@protoc_insertion_point(class_scope:GridProtection.GridMonitorTime)
    ))
  ,

  Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), dict(
    DESCRIPTOR = _GRIDPROTECTION_HEADER,
    __module__ = 'grid_protection_pb2'
    # @@protoc_insertion_point(class_scope:GridProtection.Header)
    ))
  ,
  DESCRIPTOR = _GRIDPROTECTION,
  __module__ = 'grid_protection_pb2'
  # @@protoc_insertion_point(class_scope:GridProtection)
  ))
_sym_db.RegisterMessage(GridProtection)
_sym_db.RegisterMessage(GridProtection.GridMonitorTime)
_sym_db.RegisterMessage(GridProtection.Header)


# @@protoc_insertion_point(module_scope)
